### ISSUE TITLE
Prep the XML 2.2 before importing in Archi

### ISSUE THREAD

**Issue by Jonasvdbo** [NBility-Model/NBility-business-capabilities-Archi#6]

**Comment by Jonasvdbo** [comment]
In local version of Archi prepration

**Comment by Jonasvdbo** [comment]
Both English and Dutch model

**Comment by sefanja** [comment]
NBility 2.2 is already live on the main branch, bilingual with the use of label expressions (at least for now - since maintaining two separate repositories and keeping them in sync is near to impossible).
